### ISSUE TITLE
Cisco 8000v

### ISSUE THREAD

**Issue by berkutcloud** [hellt/vrnetlab#170]
Sorry @hellt ,

The issue cannot be closed like this: https://github.com/hellt/vrnetlab/issues/169

There is a problem. You claim that Cisco 8000 is supported by containerlab: https://containerlab.dev/manual/kinds/c8000/. But it is not in the case. We have Cisco 8000 qcow2 and we would like to get the container image created using vrnetlab. Please, make it up in the way other VM to container images are done.

Regards,
Berkut Cloud

**Comment by hellt** [comment]
This is an open source project which relies on contributions from the community. 

Someone from Cisco or close to Cisco created the integration for containerlab, but they did not contribute a way to create the containerlab compatible image. 

Fwiw I heard that Cisco customers are able to get the containerlab compatible image from the vendor. 

I will leave this open so that maybe someone who knows how 8000k operates will be willing to work on it, but the containerlab team don't have access to this information

**Comment by berkutcloud** [comment]
You claim support for it. if Open Source projects claims that something is supported, then there shall be some Open Source documentation how to make that working. Otherwise, it doesn't seem to be supported. So looking forward for details from your or containerlab community how this is working.

**Comment by hellt** [comment]
It seems the support for cat8k is being added in https://github.com/vrnetlab/vrnetlab/pull/341

Contributors can port this code to this fork to add support for it

**Comment by mzagozen** [comment]
I do not have a definitive timeline, but I can give this port a shot (vrnetlab fork and containerlab node kind) in the next couple of weeks, if there are no other takers. I have been reading up on the vrnetlab networking changes and ISTM the changes in a concrete platform `launch.py` are minimal.

**Comment by hellt** [comment]
thanks @mzagozen, appreciate.

indeed, I do not anticipate any blocking changes for the platform launch.py you have in the upstream vrnetlab. Can be that a few minor tweaks would be required with regards to the common.py diverted changes, but they should also be rather minimal.

**Comment by hellt** [comment]
added with containerlab v0.54.0, thanks @mzagozen 

https://containerlab.dev/manual/kinds/vr-c8000v/
