### ISSUE TITLE
TFTP configuration for SROS License

### ISSUE THREAD

**Issue by bclasse** [hellt/vrnetlab#41]
Hi,

I was testing a simple VSR deployment and couldn't manage to retrieve the license.
`docker run -d --privileged --name my-sros-router vrnetlab/vr-sros:20.5.R2`

I identified the root cause in the following configuration :

```
root@41529a4f35f9:/# cat /etc/default/tftpd-hpa
/etc/default/tftpd-hpa

TFTP_USERNAME="tftp"
TFTP_DIRECTORY="/srv/tftp"
TFTP_ADDRESS=":69"
TFTP_OPTIONS="--secure"

```
The location of the tftp server points to /srv/tftp, while the license is stored under /tftpboot.
Did I miss anything ? Or should the location of tftp server points to /tftpboot ?

```
A:vSIM# show bof
===============================================================================
BOF (Memory)
===============================================================================
    primary-image    cf3:\timos\
    primary-config   tftp://172.31.255.29/config.txt
    license-file     tftp://172.31.255.29/license.txt
```

Kind regards,
Bastien

**Comment by bclasse** [comment]
Hi,

Turns out _launch.py_ can't find /tftpboot/ folder on VM. 
Declaring it in Dockerfile solves the issue above.

**Comment by hellt** [comment]
Hi @bclasse 
yes, the images in this fork are meant to be used with [containerlab](https://containerlab.srlinux.dev). There we mount the tftpboot dir on start, so that issue is not present.

In any case, you need a license to run SR OS, and to provide this license, you need to mount it like something similar to that `-v $(pwd):/tfpboot` flag of the `docker run` cmd.

Let me know if you have any other questions about this issue
